version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: 'twitter-clone'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    ports:
      - '5433:5432'
